version: '3'

services:
  client:
    build: 
      context: ./client
    network_mode: "host"
    environment:
      ASYNC_ADDR: "amqp://guest:guest@localhost:5672/"
      ASYNC_NAME: "top"
      GIN_ADDR: "localhost:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      logic:
        condition: service_started
  
  logic:
    build: 
      context: ./logic
    network_mode: "host"
    environment:
      ASYNC_ADDR: "amqp://guest:guest@localhost:5672/"
      ASYNC_NAME: "top"
      RAM_ADDR: "localhost:6379"
    depends_on:
      rabbitmq:
        condition: service_healthy
      sync_logic:
        condition: service_started
    

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    
    healthcheck:
      test: "/opt/rabbitmq/sbin/rabbitmqctl status"
      interval: 2s
      timeout: 30s
      retries: 15
    network_mode: "host"
  
  sync_logic:
    build: 
      context: ./sync_logic
    environment:
      WSS: "<WSS GET_BLOCK>"
      RAM_ADDR: "localhost:6379"

      NAME_TABLE: "eth"
      MAX_COUNT_BLOCK: "100"

      DB_ADDR: "localhost:9000"
      DB_DATABASE: "default"
      DB_USERNAME: "default"
      DB_PASSWORD: ""

    depends_on:
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_started

    network_mode: "host"

  clickhouse:
    image: bitnami/clickhouse:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: "host"
    healthcheck:
      test: /opt/bitnami/clickhouse/bin/clickhouse-client clickhouse://localhost:9000 --query "SELECT 1"
      interval: 5s
      timeout: 3s
      retries: 5
  
  redis:
    image: redis:latest
    network_mode: "host"